

GET http://localhost:5018/games

###
GET http://localhost:5018/games/3

###
POST http://localhost:5018/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kids",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}
